### ISSUE TITLE
"OpenGL Error: 1282 (Invalid Operation)"

### ISSUE THREAD

**Issue by bmcwal** [sp614x/optifine#2114]
Hello everyone,

I'm getting a strange message pop up whenever I use Optifine. It's been happening since 1.13.1 and continues into 1.13.2

The chat/command will display "OpenGL Error: 1282 (Invalid Operation)" every 10 seconds or so which can be really tedious in multiplayer when you're trying to follow a chat.

I've tried everything I can think of. Full/clean reinstall of Minecraft, updating Java, updating Windows, updating graphics drivers, but the moment I run the game with Optifine it pops up again.

Has anyone else had this bug, and if so, how do you get rid of it? I am hoping to avoid having to play Minecraft without Optifine, but that's the only way I can stop it happening at the moment.

**Comment by bmcwal** [comment]
Actually getting a 2nd error in there now, "1281 (Invalid Value)"

**Comment by AndanteDevs** [comment]
Before the issue is fixed, there is a setting to turn off OpenGL errors. I believe it is `Options...` -> `Video Settings` -> `Other` -> `Show OpenGL errors`.

Hope this helps.

**Comment by bmcwal** [comment]
That is _really_ useful, AndanteDevs, thank you!

**Comment by cybercatgurrl** [comment]
I am also getting this error periodically on 1.12.2 using sildurs vibrant shaders.

**Comment by sp614x** [comment]
Mixed with the OpenGL errors are also some NullPointerExceptions which may be related:
```
Caused by: java.lang.NullPointerException
	at cfc.d(SourceFile:199)
	at crd.a(SourceFile:1809)
	at lo.a(SourceFile:122)
	at lo.a(SourceFile:16)
	at ix.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:21)
	at ix$$Lambda$1032/114356890.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at k.a(Util.java:157)
```

**Comment by sp614x** [comment]
The OpenGL error is very strange: `OpenGL API ERROR: 1281 (GL_INVALID_VALUE error generated. View frustum must not have a zero values of: (right-left), (top-bottom), or (zFar-zNear).)`
As if the view frustum is incorrectly defined.

**Comment by sp614x** [comment]
What OS, GPU, drivers?
F3 debug screenshot?

**Comment by cybercatgurrl** [comment]
Windows 10 1909. GTX 1070, nvidia driver version 441.41. I'll try to get the screenshot in a bit.

**Comment by cybercatgurrl** [comment]
![2019-12-05_22 03 59](https://user-images.githubusercontent.com/7425159/70229948-58824400-17ab-11ea-913b-36d2790fc42f.png)
Here's the debug screenshot.

**Comment by sp614x** [comment]
@cybercatgurrl you are running Forge with 59 mods loaded. Most probably a conflict with one of the installed mods.

The original problem is OptiFine standalone, no other mods.

**Comment by Hilife808** [comment]
so im having the same errors but my game is a black screen. i can open my inventory and see my hotbar. im running on 1.7.10. i'll post the mod list below. 
![2019-12-31](https://user-images.githubusercontent.com/53022030/71630071-33fc6a80-2ba5-11ea-91be-82a1fe79d69b.png) 
Thank you and pls get back to me asap. :)

**Comment by asbyth** [comment]
should probably update optifine, E3 is outdated

**Comment by Hilife808** [comment]
thanks man ill try it out and get back to you if it works or not

**Comment by Hilife808** [comment]
also do you think you can help me with some other issues im having. either through email, here or discord.

**Comment by Hilife808** [comment]
also updating the optifine version did not work still the same

**Comment by Jennifercutixx** [comment]
If u are running shaders. It can sometimes give u a black screen bc the shaders is trying to add visual effects but cant bc a mod is doing the same thing. And for ur error 1282. that is also a shader error message. which is to do with visals again. This error ecours mostly when u have a dimension mod installed since dimension mods can cause shaders issue's.
How i fixed that error is just turn off the gui errors in your settings. but other then that with the black scrren i would contact the shader owner if still avalible for the issue to be resolved.
Most of all its a shader visual conflict

**Comment by progamerdixie** [comment]
I have the same problem i select a shader and when its on the screen is black and i get the error Open GL Error 1282 (invalid operation).

![Minecraft_ 1 15 2 - Singleplayer 7_20_2020 8_14_40 PM](https://user-images.githubusercontent.com/68571972/87998606-67adcc00-cac6-11ea-9efe-a7192490a6ef.png)

![Minecraft_ 1 15 2 - Singleplayer 7_20_2020 8_15_15 PM](https://user-images.githubusercontent.com/68571972/87998616-6da3ad00-cac6-11ea-95fa-e94b267de183.png)

**Comment by Deviouslrd** [comment]
You should be able to just reload the shader, and it should work. also why not use pre30

**Comment by progamerdixie** [comment]
i have tried to reload the shader and the same thing happened

**Comment by daryduck14** [comment]
Hi, I am also having this error however I am not getting the black screen however my shader still isn't loading, I also used a preview version of optifine because there was no 1.16 version, could that be the issue or do you think it was the shader? (the shader is SEUS renewed and is v1.0.1) How do I fix this error and load my shader? :(

**Comment by daryduck14** [comment]
Hi, I am also having this error however I am not getting the black screen however my shader still isn't loading, I also used a preview version of optifine because there was no 1.16 version, could that be the issue or do you think it was the shader? (the shader is SEUS renewed and is v1.0.1) I also don't have any mods loaded on the game. How do I fix this error and load my shader? 
![image](https://user-images.githubusercontent.com/68855231/88542767-dd59f080-d00e-11ea-867b-ebafe5e0caac.png)

**Comment by progamerdixie** [comment]
Yes I have the same problem too with a different shader the other one gave me the black screen but trying a different one I got the error and can see my screen but the shader doesn’t work

**Comment by progamerdixie** [comment]
Also I did get the newer preview optfine pre 30

**Comment by AiJermain** [comment]
[2020-08-05-5.log.gz](https://github.com/sp614x/optifine/files/5029190/2020-08-05-5.log.gz)
So yea this is happening :/ Can't launch the game at all

**Comment by WilliamD47** [comment]
This happens for me on mac but it does tell me that my device doesn't support it and I get some bits of the screen staying still

**Comment by whodislolxd** [comment]
I have a similar problem with Immersive Engineering. I want to try the mod but if nobody can help then I don't mind removing it. This mod makes the OpenGL Error message spam every 5/10 seconds but also makes it so I can see parts of caves through the surface of water. I tried removing it and these problems don't exist. Images that may help and list of mods are below:
![image](https://user-images.githubusercontent.com/22898630/103488951-bafaa900-4dde-11eb-97cc-6c7bbea16506.png)
![image](https://user-images.githubusercontent.com/22898630/103488989-fdbc8100-4dde-11eb-8331-0a04ad6a5b89.png)
List of mods:
- Applied Energistics 2
- Immersive Engineering
- Industrial Foregoing
- Mekanism
- Mekanism Additions
- Mekanism Generators
- Mekanism Tools
- OptiFine 1.16.4_HD_U_G5
- Titanium
- (and Forge, obviously)
Also, if OptiFine is the cause, I can try removing to try but would prefer different alternatives.

**Comment by michealREEEEE** [comment]
My brother is running Aristois 1.16.5 with optifine and baritone on his survival hack game but it shows Open GL Error 1282 (Invalid Operation) can someone help please?

**Comment by Jennifercutixx** [comment]
Just regular shader errors. Always happens with optifine. To solve this issue of not getting the text. Go into options, video settings, Other settings and turn show GL errors: to off.

**Comment by THEB34Rw** [comment]
Hola juego forgeoptifine en la 1.12.2 y al poner shaders mi mano y el nether se ven o negros o blancos adjunto imagen con mis componentes y shader 
![image](https://user-images.githubusercontent.com/79407161/108626561-bd60a300-741e-11eb-8f5c-c3c1fd1ca91e.png)
 Asi se ve mi mano 
![image](https://user-images.githubusercontent.com/79407161/108626572-ca7d9200-741e-11eb-9598-23609a602ea7.png)
ese no es color de mi skin 
Adjunto captura de los mods que uso
![image](https://user-images.githubusercontent.com/79407161/108626589-dd906200-741e-11eb-85d3-6f0189ac16c7.png)

**Comment by soopi-n** [comment]
The thing is, im getting the same problem with Lunar Client (im using it because my normal minecraft crashes when i open it, it would be helpful if someone helps) 
![image](https://user-images.githubusercontent.com/79798869/109423398-dc939d80-79e7-11eb-8bab-cb201bb14733.png)

**Comment by CaKePopS2k17** [comment]
> Hello I play forgeoptifine in 1.12.2 and when I put shaders my hand and the nether are either black or white I attach an image with my components and shader
> ![image](https://user-images.githubusercontent.com/79407161/108626561-bd60a300-741e-11eb-8f5c-c3c1fd1ca91e.png)
> This is what my hand looks like
> ![image](https://user-images.githubusercontent.com/79407161/108626572-ca7d9200-741e-11eb-9598-23609a602ea7.png)
> that is not the color of my skin
> Attached capture of the mods that I use
> ![image](https://user-images.githubusercontent.com/79407161/108626589-dd906200-741e-11eb-85d3-6f0189ac16c7.png)
> Plis if anyone knows how to solve it tell me and in the chat it also says OpenGl 1282

Man I actually have found out how to solve this problem. Your mod list screenshot helped me a lot. Delete "albedo". I don't know why but this mod is ruining the visuals of your game.

**Comment by psypher801** [comment]
Ran into the OpenGL 1282 error myself just now.
I was able to resolve the conflict by referring to the logs, where I found that at least in my case, it was Pneumaticraft having issues drawing the overlay for the pressure gauges.
Look at your latest log, scroll to the bottom and find the last occurrence of the error.
Read through the error and look for mention of a mod you have used or a default MC setting that is conflicting with Optifine.

Here is my error for reference. 
Don't get overwhelmed if you don't understand everything.
Your just looking to find what is causing the issue for OpenGL so just look for a reference to something for you to investigate.
Then you can disable the mod or delete any error causing items in game and the error should no longer be an issue. 
Much better solution that just ignoring it and suffering the performance cost.
Hopefully this helps others figure out how to troubleshoot their specific conflict.
`[20:28:13] [Client thread/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. State(s) are invalid: primitive mode match.)
java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GL11C.glDrawArrays(Native Method) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GL11.glDrawArrays(GL11.java:1879) [lwjgl-opengl-3.2.2.jar:build 10]
	at com.mojang.blaze3d.platform.GlStateManager.drawArrays(GlStateManager.java:975) [?:?]
	at net.optifine.shaders.SVertexBuilder.drawArrays(SVertexBuilder.java:360) [?:?]
	at net.minecraft.client.renderer.WorldVertexBufferUploader.func_181679_a(WorldVertexBufferUploader.java:83) [?:?]
	at net.minecraft.client.renderer.Tessellator.func_78381_a(Tessellator.java:33) [?:?]
	at me.desht.pneumaticcraft.client.util.GuiUtils.drawPressureGauge(GuiUtils.java:95) [?:1.14.4-1.0.8-22]
	at me.desht.pneumaticcraft.client.model.module.ModelPressureGauge.renderDynamic(ModelPressureGauge.java:55) [?:1.14.4-1.0.8-22]
	at me.desht.pneumaticcraft.client.model.module.ModelPressureGauge.renderDynamic(ModelPressureGauge.java:13) [?:1.14.4-1.0.8-22]
	at me.desht.pneumaticcraft.client.model.module.ModelModuleBase.render(ModelModuleBase.java:25) [?:1.14.4-1.0.8-22]
	at me.desht.pneumaticcraft.client.render.tileentity.RenderPressureTubeModule.render(RenderPressureTubeModule.java:68) [?:1.14.4-1.0.8-22]
	at me.desht.pneumaticcraft.client.render.tileentity.RenderPressureTubeModule.func_199341_a(RenderPressureTubeModule.java:21) [?:1.14.4-1.0.8-22]
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_203602_a(TileEntityRendererDispatcher.java:201) [?:?]
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:154) [?:?]
	at net.minecraft.client.renderer.WorldRenderer.func_215326_a(WorldRenderer.java:989) [?:?]
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:362) [?:?]
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4243) [?:?]
	at net.minecraft.client.renderer.GameRenderer.func_78471_a(GameRenderer.java:1029) [?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:795) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:890) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.2.20.jar:28.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$431/1353093587.call(Unknown Source) [forge-1.14.4-28.2.20.jar:28.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?]`

**Comment by skyyxX** [comment]
hi, i have been having this problem and idk how to fix it, ive tried praticly evrything and nothing changes
![Captura de pantalla (147)](https://user-images.githubusercontent.com/86997530/124540549-3ae0ea80-dde5-11eb-878d-f5e461a16ee9.png)
![Captura de pantalla (148)](https://user-images.githubusercontent.com/86997530/124540590-5815b900-dde5-11eb-832a-6dae464d3942.png)

**Comment by ajs256** [comment]
I am also experiencing this issue, my game is vanilla except for Optifine, running through MultiMC.

The relevant line of my game log is `[21:23:48] [Render thread/ERROR]: [OptiFine] OpenGL error: 1282 (Invalid operation), at: Expand VBO`. 

Minecraft 1.17.1, on macOS 11.5.2 on Intel.

**Comment by sp614x** [comment]
The "OpenGL Error: 1282" is a general error which means "something is wrong". 
OpenGL uses this error for many different problems at many different places.
-
The original issue from @bmcwal is for 1.13 about invalid frustum size with Forge and mods.
@cybercatgurrl reports it for 1.12 and running with shaders.
@Hilife808 reports it for 1.7.10 and Forge + mods.
@progamerdixie reports it for 1.15.2 with shaders.
@WilliamD47 reports it for a Mac.
@michealREEEEE reports it for https://github.com/cabaletta/baritone
@soopi-n reports it for Lunar client
@skyyxX reports it for 1.17 with shaders.
@ajs256 reports it for 1.17 on Mac running with MultiMC.

Those are different problems that need separate issues.

**Comment by shaazx001** [comment]
i having an error that says opengl error:1282 invalid operation 
otherwise when i launch the game it just gets stuck at the  loading screen with thedirt background pls help me some one

**Comment by ajs256** [comment]
@shaazx001 please open a new issue report

**Comment by lllL3G10nlll** [comment]
Error 1281 I solved it, enter the server, then press the ESC key, then, Graphics, Various Options, Reset all the configuration, Then yes, and reset all the unnecessary activity that you used.

**Comment by JeaumP** [comment]
In my case, the error stopped occurring when I turned off the "Render Regions" option of optifine.

**Comment by sircorneilous** [comment]
how do i  fix  this error>> message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error'  im on vanilla by the way.

**Comment by sircorneilous** [comment]
the ting is im on complete vanilla and im getting this error

**Comment by ajs256** [comment]
@sircorneilous please open a new issue report.

**Comment by Ezio-realLOSTINSOUND** [comment]
I am having kind of the same problem. My game says in chat "OpenGL Error 1282" and then completely crashes. If anyone can help, it would be appreciated!
