### ISSUE TITLE
Forge 1.13 is not detecting OptiFine

### ISSUE THREAD

**Issue by GGWarriorWP** [sp614x/optifine#2148]
I know forge is still in early dev and not viable for playing or even playtesting, but it seems forge does not detect optifine at all when put in the mods folder.

**Comment by realjackasterisk** [comment]
OptiFine 1.13 was developed before any version of Forge 1.13 was even available, so this is not really surprising.

**Comment by sp614x** [comment]
Looking at the new Forge patching system and trying to find a way that OptiFine can use.
https://github.com/cpw/modlauncher

**Comment by JacobTDC** [comment]
Could this potentially be done by merging the forge and OptiFine .json files?

**Comment by realjackasterisk** [comment]
pretty sure that's not how it works

**Comment by JacobTDC** [comment]
I don't know... I've found that pretty useful for merging other things before. Although, I can't figure out how to get it to work for Forge + OptiFine... It may well be impossible, so that's why I asked.

**Comment by sp614x** [comment]
OptiFine is mostly updated to be compatible with Forge 1.13.2.
One standing problem is that Forge can't load the OptiFine class transformer from the mods folder.
It only works when OptiFine is installed as a library in the classpath.
@cpw knows what is missing and has plans how it can be fixed.

**Comment by LafinJack** [comment]
"It only works when OptiFine is installed as a library in the classpath."

Thank you! So we just drop it in there?

**Comment by Tokenyet** [comment]
Glad to hear that Forge 1.13.2 is working on! I suggested that you could make the issued **pinned** on the issue page. This could reduce a bit the same duplicated question :P

**Comment by NachoMans** [comment]
How do I install it as a library in the classpath

**Comment by Quavelen** [comment]
> How do I install it as a library in the classpath

I would be *very* interested in an explanation for this as well lol.

**Comment by Cadiboo** [comment]
You would need the developer version of OptiFine (which only sp614x has) loaded into a 1.13.2 Forge mod development workspace. This would put OptiFine on the classpath before Forge loads.
You could also probably do it by making a separate program to launch minecraft that would load OptiFine’s classes before launching Forge.
The Forge devs are currently away/tied up with their real jobs/working on more important stuff/maintaining 1.12.2/updating their mods to 1.13.2 right now, but they’re going to work on this soon:tm:
All of Forge is open source so you could also submit a PR to fix/add this [here](https://github.com/cpw/modlauncher)

**Comment by Quavelen** [comment]
Well, thank you for that explanation @Cadiboo. Since I certainly don't have access to sp614x's dev version, and I don't have the knowledge/knowhow to make a program to do that, it's out of my reach. 

I'm aware the Forge devs are busy, and working hard. If I was remotely intelligent enough to offer help, I would. Pretty sure I'm below average though, and my lack of any basic understanding of any code, also puts a wrench in that. 

Think of my above interest in the library classpath thing, as a "wait, we can use it before it's released?" moment of thought. Your explanation confirms that, but also tells me it's impossible for me lol. So thank you again.

**Comment by Cadiboo** [comment]
The actual issue is that Forge only loads OptiFine’s patch application code when OptiFine is on the classpath (i.e. in a development environment or pre-loaded by something else), Forge doesn’t load OptiFine’s classes from the mods folder (yet). 99% of the work to get Forge and OptiFine to be compatible has been done and as soon as Forge changes this OptiFine will be able to be loaded as a mod by Forge (except for the fact that OptiFine doesn’t contain a mods.toml file to identity it as a mod)

**Comment by xfl03** [comment]
@Cadiboo 
Not only the problem of mods.toml .
1.13.2 FML uses a new transformation system named [CoreMods](https://github.com/MinecraftForge/CoreMods). It only allows mod to transform class using JavaScript, OptiFine did not make it yet, which causes FML does not recognize and load it.
In FML before 1.13.2, FML can load LaunchWrapper [Tweaker](https://github.com/Mojang/LegacyLauncher/blob/master/src/main/java/net/minecraft/launchwrapper/ITweaker.java), but now it is replaced with [ModLauncher](https://github.com/cpw/modlauncher), it is the reason why OptiFine cannot be loaded now.

**Comment by Barteks2x** [comment]
You are right that it's not really about mods.toml. But the issue isn't that the new transformation system is different, but that it actually has features that aren't fully implemented yet. OptiFine won't use the javascript coremod system. If I understand it right, OptiFine will use the system that that is used by the CoreMods system. It works fine for CoreMods, because it's on the classpath. And FML can't load something like this from mods folder yet. When option to load it is implemented, then optifine will work with forge.

**Comment by Cadiboo** [comment]
The mods.toml issue thing is an issue with OptiFine, without it everything should still work (ServicePlugins are completely separate from mods AFAIK), but users won’t be able to see OptiFine as an installed mod and it won’t show up anywhere without it. It’s a small issue that is easily fixable if sp614x *wants* users to be able to see OptiFine in the mods list.

OptiFine does not use the new CoreMods system at all, it uses a ServicePlugin from ModLauncher (I think, I haven’t been able to find anything in the OptiFine HD_U_E8-pre mod jar).

**Comment by sp614x** [comment]
The latest preview can't be loaded as a library. It would need to be packed differently with SRG classes and the forge class transformer configuration added.

**Comment by NachoMans** [comment]
1.14 is out and 1.13 optifine isn't even ready for forge lol.

**Comment by realjackasterisk** [comment]
because *forge* isn't ready for optifine

**Comment by LafinJack** [comment]
Because Mojang keeps changing everything in the underlying structure of the game and Forge and Optifine are being written for free by volunteers.

**Comment by mrcoffee1026** [comment]
really just read a changelog or two... less speculation == a lot less confusion about this:
OptiFine 1.13.2_HD_U_E8_pre1
 - fixed shader programs above composite9 and deferred9 (#2251)
 - fixed translucent block ordering with shadowmap (#2287)
 - fixed shaders normal/specular textures (#2286)
 - fixed structure void rendering (#847)
 - internally compatible with Forge 25.0.90 (can't be installed yet)
(05.04.2019)

**Comment by Cadiboo** [comment]
> internally compatible with Forge 25.0.90 (can't be installed yet)
(05.04.2019)

Means that OptiFine’s patches are compatible with Forges patches. It doesn’t mean that it’s ready to be loaded by Forge.

**Comment by mrcoffee1026** [comment]
Yes, I think that's why they said "can't be installed yet"

**Comment by GGWarriorWP** [comment]
I have been told that forge is now able to load optifine from the mods folder, but it still doesn't work for me using optifine E7

**Comment by Cadiboo** [comment]
> The public preview can't be loaded as a library yet. It would need to be packed differently with SRG classes and the forge class transformer configuration added.

**Comment by NKSHV** [comment]
It still does not work

**Comment by Vexima** [comment]
You need to wait. Forge compatibility is coming soon - Forge has the necessary stuff to make OptiFine work - we just need to be patient. Coding isn't done instantly, but it's now possible so expect it soon!

**Comment by mrcoffee1026** [comment]
Actually, given the quantity of releases of optifine without forge support - and only for 1.14+ - I doubt they will be further implementing compatibility for 1.13.  As many plugin developers have taken this approach as well: abandoning 1.13 as unfixable, and moving on to 1.14 instead.  What I would hope for ijn the future is any indication that they intend to make 1.14 compatible with forge again, ever... as the increasing number of releases and pre-releases without suggest otherwise.

**Comment by Vexima** [comment]
Good point - I'm usually talking about 1.14. Yes, I don't think it will come for 1.13 - only 1.14.3/.4

**Comment by Mohamedking898** [comment]
Progresses?

**Comment by SupinePandora43** [comment]
@Mohamedking898 nothing...

**Comment by Vexima** [comment]
I still think that 1.13 to 1.14.2 (possibly 1.14.3) will never have Forge support, unless an mod comes along that allows Forge and OptiFine to work (ie [OptiFabric ](https://www.curseforge.com/minecraft/mc-mods/optifabric) for Forge).

**Comment by Studio528-real** [comment]
I agree with vexima for the most part, its likely that forge support will come for 1.14.3 if 1.14.4 doesn't come out first, forge has added what was needed for optifine so now its just a waiting game for sp614x to update optifine, but its most likely that 1.13-1.14.2 will not get forge, mainly bc forge doesn't have what's needed for optifine to be compatible in those versions and probably won't be updated to have them.

**Comment by sp614x** [comment]
Added all Forge 1.14.3 patches to OF. Now Forge crashes in a very strange way.

**Comment by epicmarkvan** [comment]
> Added all Forge 1.14.3 patches to OF. Now Forge crashes in a very strange way.

Strrange as in "Optifine still won't be compatible for a bit" or "Funny but an easy fix"?

**Comment by sp614x** [comment]
Crash fixed, now OF can run with Forge when installed as a library.
Next step is to make it load from the "mods" folder.

**Comment by epicmarkvan** [comment]
> Crash fixed, now OF can run with Forge when installed as a library.
> Next step is to make it load from the "mods" folder.

How do I install OF as a library? Really want to use them together.

**Comment by Quavelen** [comment]
> > Crash fixed, now OF can run with Forge when installed as a library.
> > Next step is to make it load from the "mods" folder.
> 
> How do I install OF as a library? Really want to use them together.


Please see the replies after my comment here: https://github.com/sp614x/optifine/issues/2148#issuecomment-483034623

In a nutshell though - you can't. We, I guess. Only sp614x can, as he has the required files and whatever to do it.

**Comment by sp614x** [comment]
Loading from mods folder is generally working, but crashes with some classes.
ModLauncher needs a bugfix:
https://github.com/cpw/modlauncher/issues/31

**Comment by XanderSae** [comment]
any update yet?

**Comment by Zombiella** [comment]
Well, in the meantime while this issue gets worked on, I've got to decide between having mods...and having shaders. D: Hmmmmmm

**Comment by bloodconfetti** [comment]
> 
> 
> Well, in the meantime while this issue gets worked on, I've got to decide between having mods...and having shaders. D: Hmmmmmm

They're working on it [here](https://github.com/cpw/modlauncher/issues/31#issuecomment-516819589)

**Comment by Zombiella** [comment]
Yeah, I figured they would be doing so pretty quickly. I chose Optifine>Forge anyway. I love Optifine <3

**Comment by sp614x** [comment]
Forge compatibility added in F4_pre1 for 1.14.4.
The fix will be backported to 1.13.x.

**Comment by axemwa** [comment]
Awesome so exited for the 1.13.2 verison, will it be preview or release? And is there a way I can be notified when it's ready? Maybe via discord bot?

**Comment by Cadiboo** [comment]
> Maybe via discord bot on a channel, or an ETA?
Check the #updates channel

**Comment by axemwa** [comment]
awesome, thanx

**Comment by sp614x** [comment]
Forge 1.13.2 can't load OptiFine because it lacks several mod loading features that are needed by OptiFine. They were added in Forge 1.14.4 and haven't be backported to 1.13.2.

**Comment by HeartyYF** [comment]
OptiFine F5 is not compatible with newer Forge (i.e. 25.0.219).

**Comment by Cadiboo** [comment]
Forge 25.x.x was made for 1.13.2.
> Forge 1.13.2 can't load OptiFine because it lacks several mod loading features that are needed by OptiFine. They were added in Forge 1.14.4 and haven't be backported to 1.13.2.

**Comment by AverageComet250** [comment]
Will forge capability ever be backported to OF 1.13.2
