### ISSUE TITLE
Screenshot size: toolbar size decreases

### ISSUE THREAD

**Issue by TheHADILP** [sp614x/optifine#352]
The toolbar size decreases with increasing screenshot size.
Picture 1(Standard Size):
![2016-11-25_19 22 58](https://cloud.githubusercontent.com/assets/16366556/20633914/9a32d8f0-b34b-11e6-862b-0e5734eb4b9a.png)
Picture 2(2x):
![2016-11-25_19 22 37](https://cloud.githubusercontent.com/assets/16366556/20633946/e2d234d4-b34b-11e6-9ecf-d12f5ef991a4.png)
The size of the toolbar decreases continually with 3x and 4x.

**Comment by sp614x** [comment]
Fixed in latest preview B2.

**Comment by TheHADILP** [comment]
The issue still persists with the new preview version.

**Comment by sp614x** [comment]
Works for me: [1x](http://i.imgur.com/nC3DGl5.png), [2x](http://i.imgur.com/3mySzFK.png). The toolbar has the same relative size.
Make sure to use latest preview B2.

**Comment by TheHADILP** [comment]
I tested it with the latest version (OptiFine_1.11_HD_U_B2) published on 1.12.16 and the issue still persists.
It happens with all sizes (2x - 4x).
The entire GUI is sized down (toolbar, chat and menus).
Example: 2x
![2016-12-01_22 49 33](https://cloud.githubusercontent.com/assets/16366556/20814156/d854059c-b818-11e6-9303-589734977d4b.png)

**Comment by TheHADILP** [comment]
Ok, so yeah it has the same relative size, but I think this is kind of confusing as the rest of the image is all scaled up.
Also e.g. the inventory is displayed in a strange way.
Example: 2x
![2016-12-01_22 57 52](https://cloud.githubusercontent.com/assets/16366556/20814365/a1bdb8f6-b819-11e6-9bf4-07e4e3ae3619.png)

**Comment by sp614x** [comment]
Updated preview B3 with a bugfix.
Now the GUI should be correctly scaled for all values of Video Settings -> GUI Scale.

**Comment by TheHADILP** [comment]
Thank you very much. It now works as expected:)
