### ISSUE TITLE
Dropped items wont become 2D when theyre on Fast Mode

### ISSUE THREAD

**Issue by Netasile** [sp614x/optifine#401]
I realised this when i was trying to get more FPS, dropped items wont become 2d like in the beta versions, they will stay 3D. I did a little bit of research and found out they will always show up as 3D, even if the game is on fast mode (14w25a snapshot) In optifine, i think this should be bringed back.

**Comment by sp614x** [comment]
Minecraft now supports dropped item stacking (grouping several items together) so performance should not be a big concern. Resource packs can define custom item models and for them it will not be possible to generate 2D icons.

**Comment by F0RMATTED** [comment]
will this be ever resolved? In 1.12 the option is still there but does nothing. I would really like to get the old rendering back as im trying to replicate a beta feel.

**Comment by Dimentive** [comment]
Since the option doesn’t do anything anymore, shouldn’t it be removed from the video settings?

**Comment by shmoobalizer** [comment]
Can we please get this resolved? It's been 3 years, I'd love to have this back in the game! Thanks <3

**Comment by Netasile** [comment]
I hope they add this back to the mod, it made such an significant framerate increase. Maybe it's removed from the game itself.Samsung Galaxy akıllı telefonumdan gönderildi.
-------- Orijinal mesaj --------Başlangıç tarihi: shmoobalizer <notifications@github.com> Tarih: 03.08.2019  06:44  (GMT+03:00) Alıcı: sp614x/optifine <optifine@noreply.github.com> Cc: Netasile <basarkaraca4455@gmail.com>, Author <author@noreply.github.com> Konu: Re: [sp614x/optifine] Dropped items wont become 2D when they are on Fast Mode (#401) Can we please get this resolved? It's been 3 years, I'd love to have this back in the game! Thanks <3

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sp614x/optifine/issues/401?email_source=notifications\u0026email_token=AF4SV6HSNO42TBLKP5FXCRTQCT5IJA5CNFSM4C2QCL72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3PGIXA#issuecomment-517891164",
"url": "https://github.com/sp614x/optifine/issues/401?email_source=notifications\u0026email_token=AF4SV6HSNO42TBLKP5FXCRTQCT5IJA5CNFSM4C2QCL72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3PGIXA#issuecomment-517891164",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by unRyker** [comment]
This really should be resolved/removed from the video settings since it doesn't do anything.

**Comment by Luke18033** [comment]
I personally don't see any reason to try and bring this back, I doubt 3D items would have a significant performance impact on any modern system. The option should just be removed.

**Comment by explodingdigg** [comment]
this is still a problem, what the hell.

**Comment by Luke18033** [comment]
The "problem" is the fact that the toggle for this still exists. 1.8 changed the way dropped items are rendered, so I don't think it's possible to reimplement this in a way that is compatible with the current model system.

**Comment by vinnyg0621** [comment]
please someone try to fix this problem. I'm making a beta world right now and this is the only problem for me in this world :(

**Comment by Luke18033** [comment]
I've never looked at the actual code, but based on what I do know, here's generally what the problem is:

In Minecraft, "2D sprite" items are not actually just sprites. The item's texture is extruded into a model, creating the 3D look seen when holding the item. Since 1.8, the way this is implemented is by setting the item to use the special parent model `builtin/generated`, with a texture applied. That generated model will then be rendered in all cases - in player's hands, on the ground, in item frames, and even in the inventory (in this case the model is seen from a front-on orthographic view, so it appears 2D). Doing this eliminates the need to have separate rendering paths for items depending on where they are - just render the item's model.

In order for this option to be fixed, a special case would need to be implemented so that generated item models dropped on the ground are replaced by non-rotating 2D sprites. Performance-wise, it's not really worth it; I doubt most modern computers would have trouble rendering 3D item models, especially with stack combining. I guess it would be useful if you're trying to recreate older versions of the game, but that's about it. So I think the option should just be removed.

(Again, I don't know what the code looks like so I might have gotten some details wrong, but this is the general idea of it.)

**Comment by vinnyg0621** [comment]
please don't remove it. I really need this to be fixed

**Comment by Luke18033** [comment]
That's the thing though, 2D dropped items already were removed by Mojang. This isn't a matter of "fixing" them, it's a matter of specifically reimplementing a feature most people won't even use (in a way that's pretty hacky IMO). I'm honestly not sure why the option hasn't already been removed and this issue closed. It doesn't seem like sp614x intends to reimplement 2D dropped items, given it's been over 6 years since they last worked and nothing has changed.

**Comment by vinnyg0621** [comment]
actually, on 1.7, dropped items on fast drop 2d
![2020-10-21_10 35 38](https://user-images.githubusercontent.com/57818441/96756746-5d32f500-1389-11eb-82e0-2dbce2826569.png)

**Comment by Luke18033** [comment]
>  Since 1.8, the way this is implemented...

**Comment by Luke18033** [comment]
Mojang officially marked this [issue](https://bugs.mojang.com/browse/MC-98184) as Works As Intended as of 1.9. That doesn't automatically rule this out for OptiFine, but it should be taken into consideration.

**Comment by Luke18033** [comment]
It's probably not a good idea to keep a completely non-functional option in the menu, just take a look at all the duplicates this issue has. I'd suggest removing the option for now, it could always be brought back later if @sp614x decides it's something they want to work on.

**Comment by Jiingy** [comment]
From my understanding, the option to change how dropped items render doesn't (and hasn't for a while) do anything at all really. Is this planned to change?

**Comment by Luke18033** [comment]
Please read the above comments.

**Comment by StereoMadnessss** [comment]
This is infuriating because I want to make minecraft look and feel like beta but the only drawback that I have found so far are the items when dropped, rendering as 3D. I think this should work again and this still has a chance to get fixed in 1.17. This feature should not be removed from optifine. Some people would want this like I do, for nostalgia purposes.

**Comment by JimmyHarmel** [comment]
I think adding sprite rendered items back would be really cool but seeing as item models are a thing now, it probably won't be coming to optifine anytime soon. They should just remove this option altogether.

**Comment by MetalKnight56** [comment]
yeah its really sad how the feature just won't work, i've been trying to find alternatives but unfortunatly have not yet found anything useful, please i beg to this feature being re added to OF

**Comment by MetalKnight56** [comment]
tbh i found a solution for having the old 2d dropped items. Theres a mod called nostalgic tweaks, its available both for fabric and forge and is constantly being developed. Its great you guys should check it out. https://www.curseforge.com/minecraft/mc-mods/nostalgic-tweaks
