### ISSUE TITLE
[1.14.4] [crash] [bug] Turning on shaders crashes the game.

### ISSUE THREAD

**Issue by Gierszu** [sp614x/optifine#4089]
## Description of Issue
**Before problem** : Game was running smoothly on BSL shaders version v7.1.04.1 on Forge 28.2.0 with OptiFine 1.14.4 HD U F5 on 1.14.4 Minecraft version and an inventory sorting mod and no resource packs. I had no other problems with no mods whatsoever, could change shaderpacks for other and everything was fine. One minor problem was that the beacon beam wasn't showing at all, with shaders on or off, no matter.

**Possible turning point** : I had installed a resource pack - BlueNerd's 1.14.4 VPlus version 1.3 - and everything was working except sometimes in chat there was a message "OpenGL error 1281" or something like that. I wanted to get rid of it, so I uninstalled Minecraft completely (deleting the .minecraft folder and even deleting the Minecraft Launcher). I read a bit, installed Forge 2.1.56 for compatibilty with OptiFine, extracted the MOD from OptiFine and placed it in the mods folder (Forge installation was correct). I only installed OptiFine, no other mods whatsoever. Around that time I also updated my device's drivers to AMD Radeon Adrenalin 20.5.1 version.

**Current problem** : Minecraft loads up correctly, I can normally play with no shaders. There are no additional shaders or mods installed. When I try to switch to internal shader (or if I have any other shader installed, for the other ones as well) Minecraft crashes. If it's internal, it sometimes doesn't crash.

## Steps to Reproduce
1. Install AMD Software Drivers 20.5.1
2. With OptiFine installed, change the shader from OFF, to anything, however internal sometimes works.

## OptiFine Version
OptiFine 1.14.4 HD U F5

## Installation Method
Standalone installer, and extraction to mods folder. Tested both.

## Fabric/Forge Version
If Forge is used, I tested on 28.2.0 and 28.1.56. Same problem on both.

## Log Files/Crash Reports
Launcher Log : https://pastebin.com/m5J2WxFQ
hs_err_pid29136 log : https://pastebin.com/C94jeDVV
latest log : https://pastebin.com/xLiZKbeM
debug log : https://pastebin.com/pkhisF7H

## F3 Debug Screenshot
When no shaders are applied :
![2020-06-14_19 47 26](https://user-images.githubusercontent.com/51073028/84600285-83470680-ae78-11ea-80e2-ac6cf77141c9.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No, it does not. This doesn't happen in any mod configuration when shaders are disabled. No matter the configuration, when any shader, including internal (sometimes), is picked, this happens.

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
Yes.
- Does this happen without any mods at all?
No - no shaders to pick with no OptiFine.
- Does this happen in OptiFine standalone?
Yes.

## Additional Information
**Specs**:
System : Windows 10
Processor : AMD Ryzen 5 1600 3.2GHz
RAM : 16GB
Allocated to Minecraft : 8GB
Graphics card : Radeon RX 580
Using AMD Radeon Adrenalin 2020
Driver Version
20.10.17.01-200525a-355166E-RadeonSoftwareAdrenalin2020

**What I tried** : 
- Forge 28.1.56 for compatibility
- No Forge, only installing OptiFine,
- No mods, no resource packs or shaderpacks at all, only OptiFine and internal shader, in which case it sometimes works,
- Updating drivers (everything is up to date now),
- Googling the problem online with those results:
I found some people experiencing similar problems, usual "fix" was random (they just waited until it was fixed) or updating the drivers. There was also a mention of deleting a specific file, but it seemed to apply only to a specific shaderpack.
My conclusion is - there could be multiple causes of the same problem. My case seems to be different than the rest, so here I am, asking for help.

**Comment by Gierszu** [comment]
Update : Following issue #4065 I reverted my AMD software to 20.4.2, and it seems to work now. I'm not closing the issue though, as that behavior still applies to the newer version of AMD Software, and I intend to perform further testing.

**Comment by sp614x** [comment]
```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.lwjgl.opengl.GL20C.nglShaderSource(IIJJ)V+0
j  org.lwjgl.opengl.GL20C.glShaderSource(ILjava/lang/CharSequence;)V+38
j  org.lwjgl.opengl.GL20.glShaderSource(ILjava/lang/CharSequence;)V+2
```
The crash is inside the AMD drivers when compiling the shaders code.

**Comment by sp614x** [comment]
Do you have FXAA in the Shaders menu enabled?

**Comment by Gierszu** [comment]
All settings are default, Antialiasing is OFF

**Comment by sp614x** [comment]
It is crashing when compiling the the post-processing shader.
Make sure Shaders -> Antialiasing is set to OFF, you can also press F4 in game to reset the post-processing shader.

**Comment by Hazmi35** [comment]
Got the same problem here.
AMD Radeon Software version: 20.5.1, no forge or fabric

**Comment by KaseyTheJackal** [comment]
I can also confirm this, Same configuration as OP, Ryzen 5 1600, RX 580.

Downgrading to 20.4.2 causes random BSODs, which is fixed when I install 20.5.1.

**Comment by 231187** [comment]
Same issue here - Radeon RX 5700 XT & Ryzen 7 3700x

**Comment by sp614x** [comment]
Looks like an AMD driver issue.
Upgrading/downgrading the driver may help.

**Comment by vinnyg0621** [comment]
I have this issue too with shaders. I upgraded my driver already!

**Comment by patatjeXD** [comment]
I have tried literally anything but I still have the same problem :( (i5 10400f, rx 5600xt), looks like this is a Radeon only problem or smth

**Comment by Abraguas** [comment]
Same issue here :(
Using latest AMD drivers for my rx470

**Comment by koderian** [comment]
same

**Comment by JaviruloPlay** [comment]
Same here

Latest drivers, Ryzen 5 1600AF & RX570 4GB

**Comment by Henrico326** [comment]
same here
RX 5500 XT, Ryzen 5 2600

**Comment by AidenWTF** [comment]
Found a somewhat Hacky Solution.

Just load ProjectLuma before any other Shader and it seems to Work fine on AMD.

https://www.curseforge.com/minecraft/customization/projectluma

**Comment by KaseyTheJackal** [comment]
> Found a somewhat Hacky Solution.
> 
> Just load ProjectLuma before any other Shader and it seems to Work fine on AMD.
> 
> https://www.curseforge.com/minecraft/customization/projectluma

I'm unsure how that would work, to be honest

**Comment by KaseyTheJackal** [comment]
> Looks like an AMD driver issue.
> Upgrading/downgrading the driver may help.

Sometimes it will help. I've switched over to Linux (Fedora 33) on my main machine, and repasted my RX 580. Still runs borderline throttling (but it's at least better), but it seemed to work fine despite my crashing (note: Not just Minecraft, the entire machine, my RX 580 is the root cause, it didn't do this with my GTX 1060 3GB)

**Comment by AidenWTF** [comment]
I dont know either.But it works for me, and its atleast worth a shot.Am 18.03.2021 17:13 schrieb KaseyTheJackal ***@***.***>:

Found a somewhat Hacky Solution.
Just load ProjectLuma before any other Shader and it seems to Work fine on AMD.
https://www.curseforge.com/minecraft/customization/projectluma

I'm unsure how that would work, to be honest
