### ISSUE TITLE
Minecraft 1.16.2 invisible mobs with Optifine

### ISSUE THREAD

**Issue by krazyoldkatlady** [sp614x/optifine#4790]
Certain mobs are randomly invisible and invincible. I can hear them and I take damage from them, but I can’t see them or kill them.
 This problem appeared only after I downloaded Optifine version 16.2 from the Optifine website. I play Minecraft java version 16.2 on my Minecraft realm. There is inly one mod installed in my realm and that mod makes it possible for one person to sleep for the rest of the players. Otherwise it’s a vanilla realm. However, i had this problem befire that mod was installed.

## Steps to Reproduce
1. What do you do... 
2. ...to find this bug?

## OptiFine Version
Self-explanatory. 

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?

## Fabric/Forge Version
**If OptiFine is installed as standalone, you can remove this section.**

## OptiFabric Version
**If OptiFine is installed as standalone, or you're using Forge, you can remove this section.**

## Other Installed Mods
*Every* single mod you have installed, besides OptiFine. Please don't leave anything out, even if you think it has nothing to do with the issue at hand. For long lists of mods, use Pastebin. https://pastebin.com/

**If OptiFine is installed as standalone, remove this section.**

## Log Files/Crash Reports
Any relevant log files. Drag and drop text files here to upload to GitHub directly, OR upload the complete contents to Pastebin. https://pastebin.com/

You can get logs from `.minecraft/logs`, and crash reports from `.minecraft/crash-reports`. 
Locating your `.minecraft` folder will depend entirely on your OS. See this page for details: https://minecraft.gamepedia.com/.minecraft

**DO NOT directly copy and paste log contents here on GitHub.**

## F3 Debug Screenshot
Minecraft's built-in debug screen provides *a lot* of useful information, and should be included even if the issue is not something that can be captured in a still image.

To open this menu, simply press `F3` on your keyboard while in-game. Please ensure the text is easily readable. Depending on the size/resolution of your monitor, you may have to adjust your GUI scale for all text to be completely visible on-screen.

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? 
   - Only OptiFine and Forge
   - Only OptiFine, OptiFabric, and Fabric
- Does this happen without any mods at all?
   - Only Forge/Fabric by itself.
- Does this happen in OptiFine standalone?
- Does this happen in Vanilla without OptiFine?
- Have you tried using a binary search to find which mods cause this issue?
   - To find conflicting mods, split your mods into 2 groups (not including OptiFine/OptiFabric, obviously). Remove one group, and test in-game. Keep the group that has the problem, and repeat until no more mods can be removed without the issue disappearing.
   - Does the issue still happen with only the remaining mods installed?
      - Forge/Fabric and remaining mods, without OptiFine

## Additional Information
Here goes any final remarks and everything else that might not fit in the previous sections.

**Comment by Regnander** [comment]
Related #4322

**Comment by EldritchScream** [comment]
I'm experiencing both this bug with mobs on the overworld and the piglin mobs from #4322 (both regular piglins and brutes), closing minecraft and reloading fixes the bug. I'm on the most recent version of optifine (1.16.2 HD U G3). #4322 says that the issue was fixed in a preview version, but was the bug reintroduced? I can't find a preview version more recent than the current version on the optifine website

**Comment by ZenithRogue** [comment]
@krazyoldkatlady please edit this issue to fill in the missing details

**Comment by N3ROO** [comment]
Yeah, that's an issue with persistent mobs. You have to restart your game to be able to see and hit them. This issue did not get fixed in 1.16.2 pre6 (although it was said it was https://github.com/sp614x/optifine/issues/4322#issuecomment-682167134). From what I've observed, it happens when the mobs go out of the render distance of the client and then go back in the client's render distance (it happened during a raid with illagers, and in the neither, with piglins - they're both persistent mobs).

**Comment by dabulue** [comment]
Please fix this problem already. IT'S BEEN 2 MONTHS

**Comment by ZenithRogue** [comment]
@dabulue you shoot be using 1.16.3 or 1.16.4 pre at this point. The bug is no longer present there

**Comment by Lythael** [comment]
> @dabulue you should be using 1.16.3 or 1.16.4 pre at this point. The bug is no longer present there

Actually yes it is. It still happens with piglins and random Overworld in 1.16.4

**Comment by Javrel** [comment]
seeing this in 16.4 with a witch and ilager in a raid, only other mod I have installed is waddles, and IVe still never seen em so not sure it is installed

**Comment by FireballFoxtrot** [comment]
Still an issue in 1.16.4. Caused me multiple deaths due to not being able to interact with piglin brutes. Thanks optifine.

**Comment by willtheoct** [comment]
> 
> 
> @dabulue you should be using 1.16.3 or 1.16.4 pre at this point. The bug is no longer present there

Still present in 1.16.4, please re-open
re-installing optifine only makes the invisible mobs visible again

**Comment by danbalam** [comment]
Yeah, I had the same issue with 1.16.3. invisible death defying mobs. These nasties couldn't be killed. I died a lot trying to recover my stuff. Thankfully I had a backup of my world.... from several days prior to a major build so I had the tough choice of keep the build and lose the goodies or load the back up with my goodies and lose the build. 
I stopped using optifine because people kept closing the bug stating it was fixed thus giving me no solution. 
Threads closed such as this one prompted me to retry now that 1.16.4 is out. 

I've now installed optifine for 1.16.4 and I can confirm that it does indeed still kill me. I started a new world and am still in the early game so I stashed a zombie villager I found in a nearby sand dune. When I went to retrieve it I was killed but couldn't see it. Night turned into day as I attempted to return for my stuff and the zombie had claimed some of my armour and then perished in the sun.

**Comment by manuelmaceira** [comment]
Still an issue on last version as of today (1.16.4) just lost an hc run to an invisible piglin while mining gold :cry:

**Comment by TelepathicGrunt** [comment]
Still present on latest. I gotten a report that Optifine is making persistent hostile mobs in structures to become invisible. This makes Optifine unusable with my mod Repurposed Structures as many of my structures spawn persistent mobs such as piglins so they don't despawn over time. And lets just say, getting attacked by a horde of armored invisible piglins is not a fun time...

**Comment by Route66lg** [comment]
The bug is still there. However, I discovered that you can shoot invisible mobs with a bow, it's the only way they'll be taking damage from a player. Almost died to invisible piglins and invisible vindicators multiple times. Running like hell, then building the small tower and shooting the bastards below usually helps, but god damn it's scary when it happens.

**Comment by lulabyte** [comment]
I just wanted to add my name to the pile, invisible mobs in 1.16.3

**Comment by ZeoKappa** [comment]
1.16.3 and I'm also still experiencing. Not trying to complain, simply wanting to give info. I've only experienced this with the Drowned, which has been stressful in my Hardcore world. 
I've tried to test without other mods, or without optifine, but it's impossible to figure out if there are invisible mobs if I can't see them.

**Comment by Lythael** [comment]
> 1.16.3 and I'm also still experiencing. Not trying to complain, simply wanting to give info. I've only experienced this with the Drowned, which has been stressful in my Hardcore world.
> I've tried to test without other mods, or without optifine, but it's impossible to figure out if there are invisible mobs if I can't see them.

There is somewhat a way that can help with tracking if there are invisible monsters nearby. Turn on subtitles and watch for quoted mob idle sounds.

**Comment by routinet** [comment]
One more reproduction here.  I've been using Forge 35.0.2 and preview_OptiFine_1.16.4_HD_U_G5_pre2.  This happens disturbingly often... at least once per session.  So far, I've had invisible and invulnerable skeletons, zombies, one baby zombie, an enderman, a creeper, and a cat.  Normal creepers are bad enough... invisible and invulnerable ends exactly like you think it would.

**Comment by Qattos** [comment]
Just got killed by an invisible witch.
Playing on 1.16.4 with latest forge and optiforge.
Had this on another world with Evokers.

**Comment by Luisito98704** [comment]
1.16.4 and it still happens to me all the time, extremely annoying.

**Comment by AGGStudios** [comment]
I can confirm it is ALSO still happening to me. 1.16.4.

**Comment by Corvus20** [comment]
This might explain why the HunterIllagers from the HunterIllagers mod are invisible, too. I too can confirm 1.16.4 has this issue

**Comment by Minecraftman2001** [comment]
Problem still persists in 1.16.5

**Comment by Lythael** [comment]
> Problem still persists in 1.16.5

Yup

**Comment by Oriansenshi** [comment]
i am running a 1.16.4 modded server with updated forge and optifine, and this happens repeatedly. my only saving grace is that the mobs still take damage from thorns so i tell my players to try to heal out of it till the mob dies. Which works fine till its a piglin brute and you are out of Gapples.

**Comment by ShamanCoder** [comment]
Problem is still there, had it in 1.16.4 and 1.16.5 with invisible piglins and drowned.

**Comment by Furious1964** [comment]
Can confirm that it still exists in 1.16.5.

**Comment by comradevdka69** [comment]
Can confirm just lost a 3 year old hardcore world due to this bug fix the piglins and drowned please

**Comment by sp614x** [comment]
Fixed in G7 for 1.16.5.
