### ISSUE TITLE
[Bug] Blurred Text including Menus with OptiFine Enabled

### ISSUE THREAD

**Issue by intraCore** [sp614x/optifine#6281]
## Description of Issue
The text in menus, inventory, hotbar are all blurred with the latest preview version of OptiFine and latest Forge.
The text on signs is also see-through but instead of showing what's directly behind it, it shows the background that I'm looking at.

Additional: If I change settings in OF that cause the game to reload, the text will be clear for a few seconds and then return to being blurry. The entire menu would be sharp text and then if I leave the money, the hotbar text (level #) will go blurry after a few seconds and the menu is blurry again if I open it.

## Steps to Reproduce
1. Have Forge installed with the pre3 OF .jar in the mods folder.
2. Open Minecraft
3. Text is blurred even with mipmaps off.

## OptiFine Version
OptiFine HD U H1 pre3

## Installation Method
The pre3 .jar is in the mods folder

## Fabric/Forge Version
Forge 1.17.1 - 37.0.73

## Other Installed Mods
AppleSkin
InventoryHUD+
Just Enough Resources
Just Enough Items
JourneyMap

## F3 Debug Screenshot

![2021-09-29_00 26 17](https://user-images.githubusercontent.com/29514173/135323953-fb727be1-8982-491e-bef6-cdb79b73c77f.png)

## Prior Testing

If you've installed using Forge/Fabric:
- Does this happen without other mods installed? I didn't remove the 5 mods I mentioned but I removed all others I had.
- Does this happen in Vanilla without OptiFine? No.

## Another Screenshot to Show Blurred Text
![2021-09-28_23 54 38](https://user-images.githubusercontent.com/29514173/135324213-18480d29-e5aa-4797-80c7-b96e99143443.png)

**Comment by intraCore** [comment]
Just wanted to comment in case the last section in the post is ignored:

After typing up this post, I removed the 5 mods and slowly tried them one by one, then with each other.
The conflicting mod causing both the blurred text and the glitched sign text is JourneyMap.
This only happens when OptiFine and JourneyMap are installed together, not with either of them alone.

**Comment by mysticdrew** [comment]
If there is something on Journeymap's side to fix this, I am all ears. But we do not touch any global text rendering.

**Comment by intraCore** [comment]
> 
> 
> If there is something on Journeymap's side to fix this, I am all ears. But we do not touch any global text rendering.

That's the same thing they told me, haha.

**Comment by intraCore** [comment]
> 
> 
> If there is something on Journeymap's side to fix this, I am all ears. But we do not touch any global text rendering.

That took me a sec... I thought you were from OF saying JourneyMap can fix it, haha. Yeah, I'm hoping someone from OF has some good input.

**Comment by mysticdrew** [comment]
Someone reported
"I just noticed a workaround for the blur with optifine - turn off optifine's Custom Fonts."

**Comment by MarsKrubb** [comment]
Has anybody found a fix for this cuz it is seriously annoying me :(

**Comment by SkeletonKing20** [comment]
Switching to the internal Shader of OF fixed it for me

**Comment by mysticdrew** [comment]
Tested with Pre9 forge 37.0.103. Issue still occurs.

**Comment by idcllo** [comment]
if this is happening when you are using journey map. i turned off waypoint beacon and that fixed it

**Comment by Rihax** [comment]
If you're using journey map, and its still happening to you. Turn off waypoint beacon. That fixed the bug for me.

**Comment by mysticdrew** [comment]
> If you're using journey map, and its still happening to you. Turn off waypoint beacon. That fixed the bug for me.
> 
> if your text is still blurry when u turn it off, refresh the font by turning off and on custom font

I am the Journeymap developer. 
It is not the beacons, it is the text that is in the labels. Optifine is doing some change to the Font#drawInBatch method that is breaking it. I have not been able to find a work around.

**Comment by Ironnix** [comment]
> 
> 
> > If you're using journey map, and its still happening to you. Turn off waypoint beacon. That fixed the bug for me.
> > if your text is still blurry when u turn it off, refresh the font by turning off and on custom font
> 
> I am the Journeymap developer. It is not the beacons, it is the text that is in the labels. Optifine is doing some change to the Font#drawInBatch method that is breaking it. I have not been able to find a work around.

I mean i have no idea about the real programming but couldn'tyou just overwrite the changes?

**Comment by mysticdrew** [comment]
> I mean i have no idea about the real programming

**Comment by GaleCarde** [comment]
I've found that by disabling all my way points in the map menu, then waiting a few minutes, the problem goes away. when another way point (like a death marker) is created, the problem immediately returns until the way point is disabled.

**Comment by nhatanh0475** [comment]
> (bump) me and a friend are also having this issue, anyone found a fix other than taking off optifine and journeymap?

Your question can be answer with GaleCarde answer:

> I've found that by disabling all my way points in the map menu, then waiting a few minutes, the problem goes away. when another way point (like a death marker) is created, the problem immediately returns until the way point is disabled.


And I can confirm this is the sole solution for now, AKA: workaround for player side. Turn off the death point auto create too.
For now to those who read this, open the link from Mysticdrew to learn more about the bug.
In short just don't use Waypont, other feature work fine.
Also no need to remove Optifine, yeah mysticdrew, I talking about you. They only need to not use your Waypoint feature and they're fine. Between your mods and a mod that require by many mods like Optifine, we can clearly see which one they gonna prefer to keep **Wink**

**Comment by mysticdrew** [comment]
@sp614x 
This is still an issue OptiFine 1.18_HD_U_H3

We should chat and figure out how to resolve this issue, either on my end or on your end. I have ruled out it has to do with FontRenderer#drawInBatch. Feel free to DM me in discord when you have time. 
I have been unable to isolate what exactly in Journeymap is causing the issue, most in part because all the current tools to get Optifine to work in development env are currently not working for 1.17.1 and 1.18. So debugging is a just random trial and error.

**Comment by mysticdrew** [comment]
This is fixed in Journeymap 1.18_5.8.0alpha5 on curseforge. 
1.17_5.8.0 will receive a fix at a later date.

**Comment by mysticdrew** [comment]
Scratch that. 
It is fixed for some users, but not for other users.

**Comment by mysticdrew** [comment]
Alright, this issue I was able to resolve on my end, it can be closed.

**Comment by NovaViper** [comment]
@mysticdrew I just installed the update and the bug is fixed! I was wondering why minecraft started looking blurry after installing optifine; then I came across this issue

**Comment by Unknown-64** [comment]
I just got a similar issue, and I don't have journeymap. I went afk and then the text went blurry. I have never had this issue before, and I have used these same mods for a while now. Even in the main menu, the bug still occurs.

**Comment by TheDivine07** [comment]
I've still this same issue using OptiFine_1.18.1_HD_U_H6 and journeymap-1.18.1-5.8.1beta4.

![2022-04-16_02 58 23](https://user-images.githubusercontent.com/12448113/163655756-f6320026-56a1-4a1d-a794-7d149aaa205b.png)

**Comment by Sooperfish** [comment]
Still happens on OptiFine_1.18.2_HD_U_H7 and journeymap-1.18.2-5.8.4 for me as well
![image](https://user-images.githubusercontent.com/5457984/169724723-cb2fc92d-25a4-44af-a2f8-4be5254c55fd.png)

**Comment by Jerome226** [comment]
Happening to me on latest JourneyMap and OptiFine, seems like the blur happens when i open the chat, which is strange.

**Comment by BigClarky** [comment]
this seems to happen with optifine + FTB chunks as well, even without journeymap

**Comment by Ropsukka1233** [comment]
> this seems to happen with optifine + FTB chunks as well, even without journeymap

Yeah it seems so. I added optifine to direwolf20 1.18 pack and the blur mode starts only and always when I open chat and then it goes away after a while. It's very weird.

**Comment by agent-LuluDodo** [comment]
This file increases the resolution of the standard font. This fixes the blurred text.
[Optifont-fix.zip](https://github.com/sp614x/optifine/files/8909324/Optifont-fix.zip)
Without:
![2022-06-15_14 41 05](https://user-images.githubusercontent.com/98981925/173829352-06acd19b-1fc4-4465-8d63-9f7c41a05c79.png)
With:
![2022-06-15_14 40 47](https://user-images.githubusercontent.com/98981925/173829304-4145c2a0-a36c-4b00-ac17-d5c7609e73f6.png)

**Comment by TuckV** [comment]
> > this seems to happen with optifine + FTB chunks as well, even without journeymap
> 
> Yeah it seems so. I added optifine to direwolf20 1.18 pack and the blur mode starts only and always when I open chat and then it goes away after a while. It's very weird.

No, did you see my comment? It's from Emojiful, not FTB Chunks.

**Comment by BigClarky** [comment]
to TuckV: Ah okay. I never use emojiful anyways so I guess I'll just play without it. thanks.
to agent-LuluDodo: thanks for this workaround.

**Comment by BigClarky** [comment]
and I don't mean to double post, but the blur would always seem to trigger for me specifically when I _entered a bed._

**Comment by LST-Staardust** [comment]
The bug occurs for me as soon as I open the chat once, then i go int oesc menu and it's gone. Repeat and it does it again. I have no Journey map installed, other mods yes but it's definitely not only JM tha makes the bug occurs.

**Comment by ContinuedOak** [comment]
> Still happens on OptiFine_1.18.2_HD_U_H7 and journeymap-1.18.2-5.8.4 for me as well ![image](https://user-images.githubusercontent.com/5457984/169724723-cb2fc92d-25a4-44af-a2f8-4be5254c55fd.png)

Ayo that's my mod, thanks for downloading it :)

**Comment by HeartStringAndy** [comment]
I'm having the same issue and not using JourneyMap. I'm currently running FTB One (for map mods I believe FTB Chunks is all that is used). I'm running Optifine with Astralex shader.

I've been reading through some of the comments about map mods using waypoints that seems to blur the text. I removed all way points and disabled the function and the font still blurred for me. Hard to say if it was clearer for longer or not, hard to guage. Sometimes it'll clear up if I pay with/change shader settings that causes some load delays, sometimes a full reboot of Minecraft is needed.

I'd really like to keep map markers on my map for navigation, though honestly I don't need the floating indicators to pin point me in the direction. Of course disabling the floating waypoints in the mod didn't seem to actually do anything (the mod's function may also be glitched).

**Comment by AlovskyOrItsMik** [comment]
all the issues and solutions arent for only optifine and journey

im not using optifine or journeymap
